### ISSUE TITLE
Non-functional Collision Tags

### ISSUE THREAD

**Issue by Sonen10** [blueskythlikesclouds/btmesh#2]
The @DEAD, @SEA, @LAVA and @DAMAGE tags don't appear to function properly. Sonic treats collision with those tags as if they have the default collision.

**Comment by blueskythlikesclouds** [comment]
As the tool now supports layers and convex shapes, having these tags functional can be accomplished. Figuring these combinations isn't something I'm going to be doing however, you need to figure that out yourself.
